### ISSUE TITLE
[Question] Filter shorcut

### ISSUE THREAD

**Issue by cassianotartari** [elementous/color-filters#3]
Hi!

Is there any shortcut to add the color filter in the content block? I'm using a full-width page with the filters on top.

Thanks

**Comment by dominykasgel** [comment]
Hi @cassianotartari,

Thank you for your question :) Are you looking for shortcode to display the color filters? If so, we don't have it. (It's a good idea to add it in the next version). You can try to make a widgetized area in the content block and add the color filters widget.

**Comment by cassianotartari** [comment]
Nice @dominykasgel, I'll try that.
